import { createApp } from 'vue';
import { createPinia } from 'pinia';
import piniaPersistedstate from 'pinia-plugin-persistedstate';
import router from './router';
import i18n from './i18n';
import App from './App.vue';
import 'virtual:uno.css';
import '@unocss/reset/tailwind.css';
import './styles/global.css';
const app = createApp(App);
const pinia = createPinia();
pinia.use(piniaPersistedstate);
app.use(pinia);
app.use(router);
app.use(i18n);
app.mount('#app');
